# Generated by Django 3.2.9 on 2021-11-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211122_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd_volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный объем встраиваемой памяти'),
        ),
    ]
